---
default_context:
  app_name: "sapphire"
  app_component_name: ""
  repo_name: "tgt-{{cookiecutter.app_name | lower | replace(' ', '-')}}{% if cookiecutter.app_component_name %}-{{cookiecutter.app_component_name | lower | replace(' ', '-')}}{% endif %}"
  gradle_version: "2.12"
  rpm_publish_artifactory_url: "http://104.155.142.149/artifactory"
  apply_download_source_plugin: "true"
  source_artifact_url: "{{cookiecutter.rpm_publish_artifactory_url}}"
  source_artifact_repo: "apps-release-local"
  source_artifact_path: "com/tgt/prz/sapphire/sapphire/0.0.15"
  source_artifact_version: "0.0.15"
  source_artifact_name: "sapphire-0.0.15.jar"
  rename_source_artifact: "true"
  renamed_source_artifact_name: "{{cookiecutter.app_name}}.jar"
  yum_artifactory_publish_repo: "yum-local"
  include_preinstall_script: "true"
  include_postinstall_script: "true"
  rpm_dependencies: "jre"
  jenkins_or_drone: "drone"
  _copy_without_render:
    - "gradlew"
    - "gradlew.bat"
    - "gradle/wrapper/gradle-wrapper.jar"
